// configure the test here
var TestConfig = {
  "TestName": "Diversity Preference Test",
  "LoopByDefault": false,
  "ShowFileIDs": false,
  "ShowResults": true,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "RandomizeFileOrder": true,
  "MaxTestsPerRun": 10,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "",
  "AudioRoot": "",
  "Testsets": 
  [{'Name': 'Angry',
  'TestID': '0015-Angry_000444.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000444.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_44_ref_Angry_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001412.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001412.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_12_ref_Surprise_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000716.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000716.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_16_ref_Happy_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001404.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001404.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_04_ref_Surprise_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000452.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000452.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_52_ref_Angry_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000456.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000456.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_56_ref_Angry_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000712.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000712.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_12_ref_Happy_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000704.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000704.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_04_ref_Happy_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001416.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001416.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_16_ref_Surprise_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001072.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001072.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_72_ref_Sad_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001066.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001066.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_66_ref_Sad_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001470.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001470.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_70_ref_Surprise_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000354.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000354.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_54_ref_Angry_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000761.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000761.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_61_ref_Happy_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001506.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001506.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_06_ref_Surprise_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001111.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001111.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_11_ref_Sad_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000435.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000435.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_35_ref_Angry_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000770.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000770.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_70_ref_Happy_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001502.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001502.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_02_ref_Surprise_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000420.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000420.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_20_ref_Angry_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001062.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001062.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_62_ref_Sad_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001461.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001461.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_61_ref_Surprise_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000794.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000794.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_94_ref_Happy_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000411.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000411.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_11_ref_Angry_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001485.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001485.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_85_ref_Surprise_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000806.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000806.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_06_ref_Happy_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000362.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000362.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_62_ref_Angry_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001120.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001120.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_20_ref_Sad_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000366.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000366.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_66_ref_Angry_TTS.wav'}},
 {'Name': 'Angry',
  'TestID': '0015-Angry_000372.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Angry_000372.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_72_ref_Angry_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000802.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000802.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_02_ref_Happy_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001054.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001054.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_54_ref_Sad_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001494.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001494.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_94_ref_Surprise_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001135.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001135.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_35_ref_Sad_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000785.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000785.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_85_ref_Happy_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001144.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001144.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_44_ref_Sad_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001152.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001152.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_52_ref_Sad_TTS.wav'}},
 {'Name': 'Happy',
  'TestID': '0015-Happy_000722.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Happy_000722.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_22_ref_Happy_TTS.wav'}},
 {'Name': 'Sad',
  'TestID': '0015-Sad_001156.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Sad_001156.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_56_ref_Sad_TTS.wav'}},
 {'Name': 'Surprise',
  'TestID': '0015-Surprise_001422.wav',
  'Files': {'A': 'audio/diversity_preference/EmoDiff/0015-Surprise_001422.wav',
   'B': 'audio/diversity_preference/MixedEmotion/Mel_22_ref_Surprise_TTS.wav'}}]
}
